
name: deploy-book

# Only run this when the master branch changes
on:
  push:
    branches:
    - main
    # If your git repository has the Jupyter Book within some-subfolder next to
    # unrelated files, you can make this run only if a file within that specific
    # folder has been modified.
    #
    # paths:
    # - some-subfolder/**

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install JDK
      run: |
        sudo apt-get update; sudo apt-get -y install default-jdk-headless
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: "3.12.x"
    - name: Install system dependencies
      run: sudo apt-get install -y libxml2-dev libxslt-dev
    - name: Install Python dependencies
      run: |
        sudo pip install -r requirements.txt
    - name: Install IJava
      run: |
        sudo ./scripts/install_ijava.sh
    # Build the book
    - name: Build the book
      run: |
        ./scripts/package_projects.sh
        jupyter-book build .
    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
